### PR TITLE
RunCompletionEvent changes

### LINKED ISSUE #248: Add Run providerId to RunCompletionEvent
Change RunCompletionEvent to

```json
{
  "id": "{{ UNIQUE_MESSAGE_ID }}",
  "specversion": "1.0",
  "source": "{{ PROVIDER_NAME }}",
  "type": "org.kubeflow.pipelines.run-completion",
  "datacontenttype": "application/json",
  "data": {
    "status": "succeeded|failed",
    "pipelineName":"{{ PIPELINE_NAMESPACE }}/{{ PIPELINE_NAME }}",
    "runConfigurationName": "{{ RUNCONFIGURATION_NAMESPACE }}/{{ RUNCONFIGURATION_NAME }}", 
    "runName": "{{ RUN_NAMESPACE }}/{{ RUN_NAME }}", 
    "runId": "{{ RUN_ID }}",
    "servingModelArtifacts": [
      {
        "name":"{{ PIPELINE_NAME }}:{{ WORKFLOW_NAME }}:Pusher:pushed_model:{{ PUSHER_INDEX }}",
        "location":"gs://{{ PIPELINE_ROOT }}/Pusher/pushed_model/{{ MODEL_VERSION }}"
      }
    ]
  }
}
```

Tasks:
- [ ] Make `runConfigurationName` and `pipelineName` namespaced
- [ ] Fill `runId` with providerId

### PR DESCRIPTION
**Pull request by jmendesky**
Closes #248 

- Make RunConfigurationName and PipelineName namespaced in all provider integrations
  - Note: v0.3.0 legacy integration is not namespaced
- Add RunId
- Extend NamespacedName:
  - make to/from string functions public
  - replace JSONMarshaller with TextMarshaller to support YAML (instead od adding YAMLMarshaller)
  - add `Empty()` convenvience method

### CODE REVIEW

File: argo/common/suite_unit_test.go [hunk 1]
```diff
@@ -43,81 +43,81 @@ var _ = Context("Marshal NamespacedName", Serial, func() {
...
 
-var _ = Context("NamespacedName.string", Serial, func() {
+var _ = Context("NamespacedName.String", Serial, func() {
 	name := RandomString()
 	namespace := RandomString()
 
 	When("all fields are provided", func() {
-		It("serialises into a '/' separated string", func() {
-			serialised, err := NamespacedName{Namespace: namespace, Name: name}.string()
+		It("serialises into a '/' separated String", func() {
```
Comment (jmendesky) [inline argo/common/suite_unit_test.go:51]:
```suggestion
		It("serialises into a '/' separated string", func() {
```

File: argo/common/suite_unit_test.go [hunk 2]
```diff
@@ -43,81 +43,81 @@ var _ = Context("Marshal NamespacedName", Serial, func() {
...
-			_, err := NamespacedName{Namespace: namespace}.string()
+			_, err := NamespacedName{Namespace: namespace}.String()
 			Expect(err).To(HaveOccurred())
 		})
 	})
 
 	When("nothing is provided", func() {
-		It("serialises into the empty string", func() {
-			serialised, err := NamespacedName{}.string()
+		It("serialises into the empty String", func() {
```
Comment (jmendesky) [inline argo/common/suite_unit_test.go:74]:
```suggestion
		It("serialises into the empty string", func() {
```

File: argo/common/suite_unit_test.go [hunk 3]
```diff
@@ -43,81 +43,81 @@ var _ = Context("Marshal NamespacedName", Serial, func() {
...
 		It("deserialises into empty name only", func() {
-			deserialised, err := namespacedNameFromString(name)
+			deserialised, err := NamespacedNameFromString(name)
 			Expect(err).NotTo(HaveOccurred())
 			Expect(deserialised).To(Equal(NamespacedName{Name: name}))
 		})
 	})
 
-	When("empty string", func() {
+	When("empty String", func() {
```
Comment (jmendesky) [inline argo/common/suite_unit_test.go:118]:
```suggestion
	When("empty string", func() {
```

File: argo/providers/kfp/kfp_api.go [hunk 4]
```diff
@@ -62,16 +64,20 @@ func (gka *GrpcKfpApi) GetResourceReferences(ctx context.Context, runId string)
...
 }
 
-func (gka *GrpcKfpApi) GetRunConfigurationNameFromJob(ctx context.Context, jobId string) (string, error) {
+func (gka *GrpcKfpApi) GetRunConfigurationNameFromJob(ctx context.Context, jobId string) (common.NamespacedName, error) {
 	job, err := gka.JobServiceClient.GetJob(ctx, &go_client.GetJobRequest{Id: jobId})
 	if err != nil {
-		return "", err
+		return common.NamespacedName{}, err
 	}
+	fmt.Println(job.Description)
```
Comment (jmendesky) [inline argo/providers/kfp/kfp_api.go:72]:
```suggestion
```

File: argo/providers/kfp/kfp_api.go [hunk 5]
```diff
@@ -62,16 +64,20 @@ func (gka *GrpcKfpApi) GetResourceReferences(ctx context.Context, runId string)
...
 
 	runScheduleDefinition := base.RunScheduleDefinition{}
 	if err := yaml.Unmarshal([]byte(job.Description), &runScheduleDefinition); err != nil {
-		return "", nil
+		fmt.Println(err)
```
Comment (jmendesky) [inline argo/providers/kfp/kfp_api.go:76]:
```suggestion
```

File: argo/providers/kfp/kfp_api.go [hunk 6]
```diff
@@ -62,16 +64,20 @@ func (gka *GrpcKfpApi) GetResourceReferences(ctx context.Context, runId string)
...
+		return common.NamespacedName{}, err
 	}
 
+	fmt.Println(runScheduleDefinition)
+
```
Comment (jmendesky) [inline argo/providers/kfp/kfp_api.go:81]:
```suggestion
```

File: argo/providers/kfp/kfp_api.go [hunk 7]
```diff
@@ -2,6 +2,7 @@ package kfp
 
 import (
 	"context"
+	"fmt"
```
Comment (jmendesky) [inline argo/providers/kfp/kfp_api.go:5]:
```suggestion
```

File: argo/providers/vai/provider.go [hunk 8]
```diff
@@ -316,11 +316,16 @@ func (vaip VAIProvider) EnqueueRun(ctx context.Context, providerConfig VAIProvid
...
 	var runId string
 
-	if runIntent.RunName.Name != "" {
+	if !runIntent.RunName.Empty() {
 		runId = fmt.Sprintf(runIntent.RunName.Name)
-	} else if runIntent.RunConfigurationName != "" {
-		runId = fmt.Sprintf("%s-%s", runIntent.RunConfigurationName, uuid.New().String())
-		runLabels[labels.RunConfiguration] = runIntent.RunConfigurationName
+	} else if !runIntent.RunConfigurationName.Empty() {
+		runId = fmt.Sprintf("%s-%s", runIntent.RunConfigurationName.Name, uuid.New().String())
```
Comment (jmendesky) [inline argo/providers/vai/provider.go:322]: not using namespaced name as the provider id as this would be inconsistent with how we treat runs. I think this should be a separate change.

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

File: argo/providers/vai/provider.go [hunk 9]
```diff
@@ -27,15 +27,25 @@ import (
...
+	RunName                   string
+	RunNamespace              string
+	LegacyNamespace 		  string
+	LegacyRunConfiguration    string
 }{
-	RunConfiguration: "run-configuration",
-	PipelineName:     "pipeline-name",
-	PipelineVersion:  "pipeline-version",
-	Namespace:        "namespace",
+	RunConfigurationName:      "run-configuration-name",
```
Comment (jmendesky) [inline argo/providers/vai/provider.go:40]: should this be `runconfiguration-name`?

File: argo/providers/vai/eventing_server.go [hunk 10]
```diff
@@ -148,13 +148,42 @@ func toRunCompletionEvent(job *aiplatformpb.PipelineJob, runId string) *common.R
...
+	}
+
+	if legacyRunConfiguration, ok := job.Labels[labels.LegacyRunConfiguration]; ok {
+		// For compatability with resources created with v0.3.0 and older
+		runConfigurationName = common.NamespacedName{
+			Name:      legacyRunConfiguration,
+		}
+	} else {
+		runConfigurationName = common.NamespacedName{
+			Name:      job.Labels[labels.RunConfigurationName],
```
Comment (jmendesky) [inline argo/providers/vai/eventing_server.go:171]: will this fail if not present?

File: argo/providers/vai/eventing_server.go [hunk 11]
```diff
@@ -148,13 +148,42 @@ func toRunCompletionEvent(job *aiplatformpb.PipelineJob, runId string) *common.R
...
+			Namespace: job.Labels[labels.RunConfigurationNamespace]}
+	}
+
+	pipelineName.Name = job.Labels[labels.PipelineName]
+	if pipelineNamespace, ok := job.Labels[labels.PipelineNamespace]; ok {
+		pipelineName.Namespace = pipelineNamespace
+	}
+
```
Comment (jmendesky) [inline argo/providers/vai/eventing_server.go:179]:
```suggestion
	pipelineName.Namespace = job.Labels[labels.PipelineNamespace]

```

**Review by paoloambrosio-skyuk — APPROVED** [review]
