### PR TITLE
Fix run completion event trigger service not showing per-request logging

### LINKED ISSUE #626: Run Completion Event Trigger not logging
**Describe the bug**
The RunCompletionEventTrigger is no longer logging on a per-request basis (the server initialisation logging is still present)

**To Reproduce**
Trigger a run and wait till it finishes successfully. There are no logs in the trigger service

**Expected behavior**
Should have a log on when the run has finished

**Version and configuration**
If applicable, add configuration details to help explain your problem.

**Logs**
If applicable, add logs of the component to help explain your problem.

**Additional context**
Introduced here https://github.com/sky-uk/kfp-operator/pull/594

### PR DESCRIPTION
**Pull request by chr12c**
Closes #626

Fix run completion event trigger service not showing per-request logging due to a regression introduced in https://github.com/sky-uk/kfp-operator/pull/594.
In that previous change, the top level context (which had the logger) was no longer being passed into the server, which was using it on a per request basis. This is because contexts should be derived on a per request basis, however when deriving the logger from the new per-request context, this broke logging since that new context did not have a logger.

In this change: introduce a unary server interceptor that will still use a new context per quest in line with golang best practices, but this time it will attach the top level logger into the context which restores logging.

### CODE REVIEW

**Comment by chr12c** [comment]
After a successful pipeline run has completed, the trigger logging is showing the event has been processed
```
{"level":"info","ts":1745838382.8460348,"logger":"main","caller":"publisher/publisher_handler.go:46","msg":"New nats publisher:","Subject":"events","Server":"nats://eventbus-kfp-operator-events-stan-svc:4222"}
{"level":"info","ts":1745838382.8462863,"logger":"main","caller":"cmd/main.go:54","msg":"Listening at","host":"0.0.0.0","port":"50051"}
{"level":"info","ts":1745838880.0093524,"logger":"main","caller":"server/server.go:55","msg":"Run Completion Event Processed","grpc_method":"/run_completion_event_trigger.RunCompletionEventTrigger/ProcessEventFeed","runId":"mlops-cpu-usage-quickstart-pipeline-rc-a-tbcl2-cbeece"}
```

File: triggers/run-completion-event-trigger/cmd/main.go [hunk 1]
```diff
@@ -55,3 +58,17 @@ func main() {
...
+
+func unaryLoggerInterceptor(baseLogger logr.Logger) grpc.UnaryServerInterceptor {
+	return func(
+		ctx context.Context,
+		req any,
+		info *grpc.UnaryServerInfo,
+		handler grpc.UnaryHandler,
+	) (resp any, err error) {
+		logger := baseLogger.WithValues("grpc_method", info.FullMethod)
+		ctx = logr.NewContext(ctx, logger)
```
Comment (TobyPinfold) [inline triggers/run-completion-event-trigger/cmd/main.go:70]:
```suggestion
		ctx = logr.NewContext(ctx, baseLogger)
```

having the grpc_method on every log line triggered within a given request is going to be overly noisy for a service with only one endpoint anyway

**Review by TobyPinfold — APPROVED** [review]

File: triggers/run-completion-event-trigger/cmd/main.go (hunk 1 above)
Comment (chr12c) [reply triggers/run-completion-event-trigger/cmd/main.go]: https://github.com/sky-uk/kfp-operator/pull/627/commits/d4425cf03cb746ecb41453053c7c334191aa72bf

**Review by grahamia — APPROVED** [review]
