### PR TITLE
Succeed RC when dependencies are not met

### LINKED ISSUE #273: RC does not go into Succeeded when it fails to fetch dependent RC
Creating a RC that reference another RC that does not exist or it hasn't produced that artifect, leaves `status.synchronizationState` and `status.conditions` empty in the resource.

### PR DESCRIPTION
**Pull request by jmendesky**
Schedules and Runs should only be created once all dependencies have been met.

This also stabilizes some previously flakey tests

Closes #273

### CODE REVIEW

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

**Comment by jmendesky** [comment]
ok to test

File: controllers/pipelines/runconfiguration_controller_decoupled_test.go [hunk 1]
```diff
@@ -232,9 +252,8 @@ var _ = Describe("RunConfiguration controller k8s integration", Serial, func() {
 
 			Expect(k8sClient.Status().Update(ctx, runConfiguration)).To(Succeed())
 
-			oldState := runConfiguration.Status.SynchronizationState
 			Eventually(matchRunConfiguration(runConfiguration, func(g Gomega, fetchedRc *pipelinesv1.RunConfiguration) {
-				g.Expect(fetchedRc.Status.SynchronizationState).To(Equal(oldState))
+				g.Expect(fetchedRc.Status.ObservedGeneration).To(Equal(fetchedRc.Generation))
```
Comment (jmendesky) [inline controllers/pipelines/runconfiguration_controller_decoupled_test.go:256]: Because the state can now change to succeeded independent of dependencies, we can no longer assert on it

File: controllers/pipelines/suite_decoupled_test.go
Comment (paoloambrosio-skyuk) [inline controllers/pipelines/suite_decoupled_test.go:1]: I would usually raise fixing flakey tests as a separate PR, but it's small and isolated enough so I think we are OK.

**Review by paoloambrosio-skyuk — APPROVED** [review]
